Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2022-11, with the labels that each got.

#2 프로젝트 생성 gradle 의존성 추가
  .gitignore
  README.md
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/boostcamp/dailyfilm/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/MainActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/boostcamp/dailyfilm/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: chore

#4 issue #3 chore: Base 적용, Hilt 적용, Activity Logging
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/DailyFilmApplication.kt
  app/src/main/java/com/boostcamp/dailyfilm/MainActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/BaseActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/BaseFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: chore

#7 issue #5 feat: Firebase 로그인 추가 (commit 정리 및 Upstream branch으로 변경)
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/repository/login/AuthRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  build.gradle
Labels: feature

#10 커스텀 캘린더 ViewPager 기능 구현 & 캘린더에 표시할 날짜 Log 출력
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/BaseFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarPagerAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/main/MainActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/bindingadapter/TextView.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/fragment_calendar.xml
Labels: feature, fix

#12 Custom Gallery 구현 (GridLayout 형식 갤러리 및 영상 미리보기)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/login/LoginRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/Result.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/VideoItem.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryPagingSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryVideoRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/ContentResolverModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/LoginModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/SelectVideoModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewHolder.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/VideoSelectListener.kt
  app/src/main/res/layout/activity_select_video.xml
  app/src/main/res/layout/item_select_video.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature

#14 RecyclerView를 이용한 월별 캘린더 구현 | 캘린더 디자인 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/adpater/CalendarAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/adpater/CalendarPagerAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/model/DateModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/model/DateState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/bindingadapter/ImageView.kt
  app/src/main/res/drawable/bg_focused_date.xml
  app/src/main/res/drawable/div_calendar_week.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_datepicker_month.xml
  app/src/main/res/drawable/ic_double_arrow_left.xml
  app/src/main/res/drawable/ic_double_arrow_right.xml
  app/src/main/res/drawable/ic_drawer_menu.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_date.xml
  app/src/main/res/layout/header_calendar_drawer.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/menu/menu_calendar_drawer.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#15 Firebase Cloud Storage에 영상 업로드
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryVideoRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/local/GalleryPagingSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/remote/GalleryDataRemoteSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/SelectVideoModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/bindingadapter/ImageView.kt
  app/src/main/res/layout/activity_select_video.xml
Labels: feature, fix

#22 실제 썸네일 적용, 다운로드 된 영상 재생 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/DailyFilmItem.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/CalendarModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/BaseActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/adpater/CalendarAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/adpater/CalendarPagerAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/model/DateModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/layout/activity_play_film.xml
  app/src/main/res/layout/item_date.xml
Labels: feature

#23 영상 편집 화면 구현 feature
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/TimeVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/res/layout/activity_trim_viedo.xml
  settings.gradle
Labels: feature

#27 영상 편집 API 호환성 해결 및 선택된 Item 표시
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryPagingSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewHolder.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/VideoSelectListener.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/res/layout/item_select_video.xml
Labels: fix, improving

#33 동영상 서버 전송 프로세스 UI 가시성 확대 및 Loading UX 개선 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/drawable-v24/ic_done.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/activity_select_video.xml
  app/src/main/res/layout/activity_upload_film.xml
  app/src/main/res/raw/lottie_loading.json
Labels: improving

#38 영상 자르기 library 한국어 Localization
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/TrimVideoActivity.kt
Labels: feature

#39 자동 로그인 기능 및 로그인 화면 프로그래스바 추가
  app/src/main/assets/lottie_loading.json
  app/src/main/java/com/boostcamp/dailyfilm/data/login/LoginRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/Result.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/LottieDialogFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/UiState.kt
  app/src/main/res/layout/dialog_lottie.xml
Labels: feature, improving

#40 영상 압축기능 구현
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/TrimVideoActivity.kt
Labels: feature, fix
