Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2022-12, with the labels that each got.

#47 Video 선택 화면 및 캘린더, 로그인, 캘린더 추가 개선 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/calendar_floating_button.json
  app/src/main/assets/lottie_loading.json
  app/src/main/assets/sound_lottie.json
  app/src/main/java/com/boostcamp/dailyfilm/data/login/LoginRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/UploadFilmDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/UploadFilmRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TimeVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/model/DateAndVideoModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/LottieDialogFragment.kt
  app/src/main/res/drawable/ic_back_button.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_select_video.xml
  app/src/main/res/layout/activity_trim_viedo.xml
  app/src/main/res/layout/activity_upload_film.xml
  app/src/main/res/layout/dialog_lottie.xml
  app/src/main/res/layout/item_select_video.xml
  app/src/main/res/values/strings.xml
Labels: fix, improving

#49 내용 작성 화면 개선
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/drawable/ic_text_button_ripple.xml
  app/src/main/res/drawable/ic_text_button_ripple_2.xml
  app/src/main/res/drawable/ic_text_gradient_36.xml
  app/src/main/res/drawable/ic_text_gradient_36_2.xml
  app/src/main/res/layout/activity_upload_film.xml
  app/src/main/res/raw/lottie_writing.json
Labels: feature, improving

#51 내용 작성 버튼 잘리는 버그 수정
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/res/layout/activity_upload_film.xml
Labels: bug, fix

#52 앱 권한 거절에 따른 로직 추가
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: chore, improving

#53 영상 데이터 Room Caching | 영상 재생 일시정지, 반복재생
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDB.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDao.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/DailyFilmItem.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/FilmEntity.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/sync/SyncDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/sync/SyncRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/UploadFilmRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/CalendarDBModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/CalendarModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/SyncModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/UploadFilmModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/model/DateModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
Labels: feature, fix, improving

#57 Custom Video Gallery Paging State에 따른 처리
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/VideoLoadStateAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/VideoLoadStateViewHolder.kt
  app/src/main/res/layout/activity_select_video.xml
  app/src/main/res/layout/item_video_load_state.xml
  app/src/main/res/values/strings.xml
Labels: chore, improving

#61 theme 적용, 앱 아이콘 변경
  app/src/main/assets/calendar_floating_button.json
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: chore

#67 API 28 이하: 영상 수정한 날짜 내림차순으로 정렬되게 수정
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryPagingSource.kt
Labels: bug, fix

#77 영상 재생시 heap 메모리 부족 상황 임시 대응
  app/src/main/AndroidManifest.xml
Labels: fix

#78 H.265 적용 영상 압축 라이브러리에 맞게 코드 수정
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
Labels: improving

#81 전체 재생, CalendarView 날짜 여러번 추가 등 버그 해결
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DatePickerDialog.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/adpater/CalendarPagerAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/custom/CalendarView.kt
Labels: bug, fix

#83 Event Wrapper 클래스 적용 및 ViewModel data 직접 접근 로직 변경
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryPagingSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/Event.kt
Labels: chore
