Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2023-01, with the labels that each got.

#85 세로모드 고정 적용
  app/src/main/java/com/boostcamp/dailyfilm/presentation/BaseActivity.kt
Labels: chore

#89 캘린더 버그 수정 및 리팩토링
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmActivityBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragmentBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/SelectVideoAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/SelectVideoViewHolder.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/VideoLoadStateAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/VideoLoadStateViewHolder.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/VideoSelectListener.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalfilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_play_film.xml
  app/src/main/res/layout/activity_total_film.xml
  app/src/main/res/layout/fragment_date.xml
  app/src/main/res/layout/item_select_video.xml
  app/src/main/res/values/dimens.xml
Labels: bug, chore

#94 Fix : PlayFilmBindingAdapter 분리 후 Uri 사용하도록 수정
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragmentBindingAdapter.kt
Labels: fix

#95 키 상수화 및 Binding 초기화
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
Labels: bug, chore

#97 Loading Dialog touch시 hide 되지 않도록 수정
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/LottieDialogFragment.kt
Labels: fix

#100 한 달 영상 전체 재생 Local Uri 이용, 전부 재생한 후 Activity 종료
  app/src/main/java/com/boostcamp/dailyfilm/data/playfilm/remote/PlayFilmRemoteDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalfilmBindingAdapter.kt
Labels: fix, improving

#103 영상 삭제, 재 업로드, 내용 수정, BottomSheet 메뉴 추가
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/DeleteFilmDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/DeleteFilmRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/local/DeleteFilmLocalDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/remote/DeleteFilmRemoteDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/playfilm/remote/PlayFilmRemoteDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/sync/SyncDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/local/LocalUriDao.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/PlayFilmModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/custom/CalendarView.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/custom/DateImgView.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmActivityViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBottomSheetBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBottomSheetDialog.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/adapter/PlayFilmBottomSheetAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/model/BottomSheetModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit_text.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_re_upload.xml
  app/src/main/res/layout/dialog_bottom_sheet.xml
  app/src/main/res/layout/fragment_play_film.xml
  app/src/main/res/layout/item_bottom_sheet.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#107 다국어 기능 추가
  app/src/main/res/layout/header_calendar_drawer.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: improving

#110 영상 비동기 압축
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/layout/activity_upload_film.xml
Labels: improving
