Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2023-07, with the labels that each got.

#168 1달 재생 화면 컴포즈 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/ui/theme/Color.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/ui/theme/Theme.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/ui/theme/Type.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: migration

#166 재생 화면 컴포즈 구현
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/adapter/PlayFilmPageAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/base/ContentShowState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/base/LottieState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/base/MuteState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/compose/PlayFilmComposeFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/compose/PlayFilmFragmentCompose.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/SettingsViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/compose/SettingComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Theme.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/dialog/CustomDialog.kt
  app/src/main/res/layout/fragment_play_film.xml
  app/src/main/res/layout/fragment_play_film_compose.xml
  app/src/main/res/values/colors.xml
Labels: feature, fix, chore, migration

#163 검색 Compose Paging 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDao.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarPagingSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchScreen.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/adapter/SearchFilmAdapter.kt
  app/src/main/res/layout/activity_search_film.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix, improving
