Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2023-05, with the labels that each got.

#144 검색 기능 추가 (날짜 범위, 키워드 기반)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDao.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/calendar/CalendarRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/dataStore/PreferencesKeys.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/DailyFilmItem.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/sync/SyncDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/sync/SyncRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/SyncModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/adapter/SearchFilmAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/SettingsViewModel.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_search_film.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/menu/menu_calendar_drawer.xml
  app/src/main/res/menu/menu_search.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, fix

#147 네트워크 미 연결 시 에러 처리
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/DailyFilmApplication.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/FirebaseModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBottomSheetDialog.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragmentBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/model/SpeedState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/CalendarUtil.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/PlayState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/network/NetworkAlertDialog.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/network/NetworkManager.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/network/NetworkState.kt
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_play_film.xml
  app/src/main/res/layout/activity_total_film.xml
  app/src/main/res/layout/activity_upload_film.xml
  app/src/main/res/layout/fragment_play_film.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/boostcamp/dailyfilm/CalendarUtilTest.kt
  app/src/test/java/com/boostcamp/dailyfilm/DateViewModelUnitTest.kt
Labels: bug, feature, chore, test

#149 네트워크 상태 누락 코드 추가 및 Conflict 정리
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/DateViewModel.kt
  app/src/main/res/layout/activity_calendar.xml
Labels: fix

#154 설정 화면 Compose 전환
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragmentBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/SettingsActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/SettingsViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/compose/SettingComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Color.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Shape.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Theme.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Type.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/dialog/CustomDialog.kt
  app/src/main/res/layout/fragment_play_film.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: migration

#155 검색 화면 Compose 전환
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/ui/theme/Color.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/ui/theme/Theme.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/ui/theme/Type.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: migration

#159 Compose Theme 통일
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/SearchFilmComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/ui/theme/Color.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/ui/theme/Theme.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/searchfilm/ui/theme/Type.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/settings/compose/SettingComposeActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Color.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Shape.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Theme.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/ui/theme/Type.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/util/dialog/CustomDialog.kt
Labels: feature, chore

#156 영상 선택 화면 Compose 전환
  app/src/main/java/com/boostcamp/dailyfilm/data/selectvideo/GalleryVideoRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoCompose.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/SelectVideoAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/SelectVideoViewHolder.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/VideoLoadStateAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/VideoLoadStateViewHolder.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/adapter/VideoSelectListener.kt
  app/src/main/res/layout/activity_select_video.xml
  app/src/main/res/layout/item_select_video.xml
Labels: migration
