Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2023-03, with the labels that each got.

#127 영상 압축 - 업로드 과정 중 오류 해결
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
Labels: bug, fix

#129 API 30 미만 키보드 감지 기능 구현
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
Labels: feature, improving

#134 한 달 전체 영상의 재생 속도 변경
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/data/dataStore/PreferencesKeys.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/dataStore/UserPreferencesRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/di/PreferenceModule.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/model/SpeedState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalfilmBindingAdapter.kt
  app/src/main/res/drawable/ic_fast.xml
  app/src/main/res/layout/activity_total_film.xml
  app/src/main/res/layout/fragment_play_film.xml
Labels: feature

#135 내용 작성 화면 ProgressBar gradient 색상 적용
  app/src/main/res/drawable/pb_custom.xml
  app/src/main/res/layout/activity_upload_film.xml
Labels: improving

#138 카메라 촬영을 이용한 영상 업로드
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/anim/anim_camera_open.xml
  app/src/main/res/anim/anim_gallery_close.xml
  app/src/main/res/anim/anim_gallery_open.xml
  app/src/main/res/anim/camera_gallery_close.xml
  app/src/main/res/drawable/baseline_close_24.xml
  app/src/main/res/drawable/baseline_photo_camera_24.xml
  app/src/main/res/drawable/baseline_picture_in_picture_24.xml
  app/src/main/res/drawable/ic_close_button.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#140 chore: playFilm dp 사이즈 변경
  app/src/main/res/layout/fragment_play_film.xml
Labels: chore
