Repository boostcampwm-2022/android02-DailyFilm, pull requests merged in 2023-02, with the labels that each got.

#116 압축률 버그 수정 & 내용 수정 화면에서 미리보기 보이기
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/layout/activity_upload_film.xml
Labels: fix

#115 string 리소스 추가 반영 (영어, 중국어, 일본어)
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: chore

#119 업로드 상태 선언 및 압축 완료 감지
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/calendar/CalendarActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBottomSheetDialog.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/model/EditState.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/trimvideo/TrimVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/layout/activity_upload_film.xml
Labels: fix, improving

#122 한달 영상 재생시 날짜순서대로 보이도록 고정
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmViewModel.kt
Labels: bug, fix

#120 Edit 수정 로직 변경, Delete Flow 삭제 및 Repository 로직 변경
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/DeleteFilmDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/DeleteFilmRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/local/DeleteFilmLocalDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/delete/remote/DeleteFilmRemoteDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/model/Result.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/UploadFilmDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/UploadFilmRepository.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/local/UploadFilmLocalDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/data/uploadfilm/remote/UploadFilmRemoteDataSource.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/login/LoginViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmBottomSheetDialog.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmFragment.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/playfilm/PlayFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/totalfilm/TotalFilmViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmViewModel.kt
  app/src/main/res/layout/fragment_play_film.xml
Labels: feature, fix, chore

#124 비디오 재생/정지 버그 수정 및 디폴트 사운드 수정
  app/build.gradle
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoActivity.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoBindingAdapter.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/selectvideo/SelectVideoViewModel.kt
  app/src/main/java/com/boostcamp/dailyfilm/presentation/uploadfilm/UploadFilmActivity.kt
  app/src/main/res/layout/activity_select_video.xml
Labels: fix
